# Generated by Django 3.0.2 on 2020-06-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': 'Bloggartikler'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='article',
            field=models.TextField(default='Artikkel', max_length=2000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='leadParagraph',
            field=models.TextField(default='Ingress', max_length=200),
        ),
    ]
